# Generated by Django 4.2.30 on 2026-09-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=80, verbose_name='Nama depan')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='Nama belakang')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=40, verbose_name='Telepon')),
                ('subject', models.CharField(blank=True, max_length=160, verbose_name='Subjek')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Diterima')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Sudah ditangani')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Alamat IP')),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Pesan kontak',
                'verbose_name_plural': 'Pesan kontak',
                'ordering': ['-created_at'],
            },
        ),
    ]
